---
version: '2'

services:
  web:
    image: lazyfrosch/icingaweb2
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - web_conf:/etc/icingaweb2
      - ./fileshipper:/etc/icingaweb2/modules/fileshipper
    working_dir: /etc/icingaweb2

  # director:
  #   image: lazyfrosch/icingaweb2
  #   depends_on:
  #     - db
  #   volumes:
  #     - web_conf:/etc/icingaweb2
  #   entrypoint: []
  #   command:
  #     - icingacli
  #     - director
  #     - daemon

  db:
    image: mariadb:10.2
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/mysql-databases.sql:/docker-entrypoint-initdb.d/mysql-databases.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: onlyforadmin
      MYSQL_DATABASE: icinga
      MYSQL_USER: icinga
      MYSQL_PASSWORD: rosebud

  icinga2:
    image: lazyfrosch/icinga2
    depends_on:
      - db
    environment:
      ICINGA_NODENAME: icinga2.localdomain
      ICINGA_CA_ENABLE: 'true'
      ICINGA_CA_TICKET_SALT: yoloops
      ICINGA_API_USER_root: icinga
      ICINGA_IDO_ENABLE: 'true'
      ICINGA_IDO_HOST: db
      ICINGA_IDO_NAME: icinga2
      ICINGA_IDO_USERNAME: icinga
      ICINGA_IDO_PASSWORD: rosebud
      ICINGA_IDO_INSTALL: 'true'
    networks:
      default:
        aliases:
          - icinga2.localdomain
    ports:
      - 5665:5665
    volumes:
      - icinga2_data:/var/lib/icinga2
      - icinga2_log:/var/log/icinga2
      #- ./icinga2:/etc/icinga2/conf.d/examples:ro

volumes:
  web_conf:
  db_data:
  icinga2_data:
  icinga2_log:
